wholeslidedata:
    default:
        yaml_source: sedeen_data.yml
        seed: 2

        label_map:
            ffff00ff: 1 #yellow
            00ff00ff: 2 #green
            000000ff: 3 #black
            00ffffff: 4 #blue

        out_labels:
            tils: 1
            tumor: 2
            calcification: 3
            cell: 4

        annotation_parser:
            module: wholeslidedata.accessories.sedeen.parser
            attribute: SedeenAnnotationParser
            labels: ${wholeslidedata:labels}
            renamed_labels: ${wholeslidedata:out_labels}

        annotation_sources: 
            filters: ['xml']
            
        batch_shape:
            batch_size: 8
            spacing: 0.5
            shape: [256, 256, 3]
            
        label_sampler:
            attribute: OrderedLabelSampler

        annotation_sampler:
            attribute: OrderedAnnotationSampler
            
        # point_sampler:
        #     attribute: RandomPointSampler
